---
- name: "Get node exporter package"
  ansible.builtin.get_url:
    url: "{{ _prometheus_node_exporter_download_url }}"
    dest: "/tmp/node_exporter-{{ prometheus_node_exporter_version }}.linux-amd64.tar.gz"
    mode: 0644

- name: "Unpack the tarball"
  ansible.builtin.unarchive:
    src: "/tmp/node_exporter-{{ prometheus_node_exporter_version }}.linux-amd64.tar.gz"
    dest: /tmp
    remote_src: true

- name: "Copy the node exporter binary to /usr/local/bin"
  ansible.builtin.copy:
    src: "/tmp/node_exporter-{{ prometheus_node_exporter_version }}.linux-amd64/node_exporter"
    dest: /usr/local/bin
    mode: a+x
    remote_src: true

- name: "Create node exporter user"
  ansible.builtin.user:
    name: node_exporter
    state: present
    system: true
    shell: /bin/false
    create_home: false

- name: "Create node exporter systemd service"
  ansible.builtin.template:
    src: "node_exporter_systemd.j2"
    dest: "/etc/systemd/system/node_exporter.service"
    mode: 0644

- name: "Reload Systemd daemon"
  ansible.builtin.systemd:
    daemon-reload: true

- name: "Start and Enable node_exporter service"
  ansible.builtin.systemd:
    name: node_exporter
    enabled: "{{ prometheus_node_exporter_service_enabled }}"
    state: started
