---
- name: "Reload Systemd daemon"
  ansible.builtin.systemd:
    daemon-reload: true
  become: true

- name: "Start node_exporter service"
  ansible.builtin.systemd:
    name: node_exporter
    enabled: "{{ prometheus_node_exporter_service_enabled | lower }}"
    state: restarted
  become: true
