---
- name: "Install Node exporter in ubuntu"
  ansible.builtin.debug:
    msg: "Install in ubuntu"
  
- name: "Get var value"
  ansible.builtin.debug:
    var: _prometheus_node_exporter_download_url
  
- name: "Get node exporter package"
  ansible.builtin.get_url:
    url: "{{ _prometheus_node_exporter_download_url }}"
    dest: "/tmp/node_exporter-{{ prometheus_node_exporter_version }}.linux-amd64.tar.gz"

- name: "Unpack the tarball"
  ansible.builtin.unarchive:
    src: "/tmp/node_exporter-{{ prometheus_node_exporter_version }}.linux-amd64.tar.gz"
    dest: /tmp
    remote_src: true

- name: "Copy the node exporter binary to /usr/local/bin"
  copy:
    src: "/tmp/node_exporter-{{ prometheus_node_exporter_version }}.linux-amd64/node_exporter"
    dest: /usr/local/bin
    mode: a+x
    remote_src: true 

- name: "Create node exporter user"
  ansible.builtin.user:
    name: node_exporter
    state: present
    system: true
    shell: /bin/false
    create_home: false
  
- name: "Create node exporter systemd service"
  template:
    src: "../../templates/node_exporter_systemd.j2"
    dest: "/etc/systemd/system/node_exporter.service"

- name: "Reload Systemd daemon"
  ansible.builtin.systemd:
    daemon-reload: yes

- name: "Start and Enable node_exporter service"
  ansible.builtin.systemd:
    name: node_exporter
    enabled: true
    state: started
